//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int CarModelYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public string DUICheck { get; set; }
        public string CoverageType { get; set; }
        public int Total { get; set; }
        public int SpeedingTickets { get; set; }
    }
}
